using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LPF.Ctl.Helper
{
    public static class FontAwesomeND
    {
        private static Dictionary<string, string> dic = new Dictionary<string, string>();
        static FontAwesomeND()
        {
            #region 初始化字典
            dic.Add("fa-500px", "&#xf26e;");
            dic.Add("fa-adjust", "&#xf042;");
            dic.Add("fa-adn", "&#xf170;");
            dic.Add("fa-align-center", "&#xf037;");
            dic.Add("fa-align-justify", "&#xf039;");
            dic.Add("fa-align-left", "&#xf036;");
            dic.Add("fa-align-right", "&#xf038;");
            dic.Add("fa-amazon", "&#xf270;");
            dic.Add("fa-ambulance", "&#xf0f9;");
            dic.Add("fa-anchor", "&#xf13d;");
            dic.Add("fa-android", "&#xf17b;");
            dic.Add("fa-angellist", "&#xf209;");
            dic.Add("fa-angle-double-down", "&#xf103;");
            dic.Add("fa-angle-double-left", "&#xf100;");
            dic.Add("fa-angle-double-right", "&#xf101;");
            dic.Add("fa-angle-double-up", "&#xf102;");
            dic.Add("fa-angle-down", "&#xf107;");
            dic.Add("fa-angle-left", "&#xf104;");
            dic.Add("fa-angle-right", "&#xf105;");
            dic.Add("fa-angle-up", "&#xf106;");
            dic.Add("fa-apple", "&#xf179;");
            dic.Add("fa-archive", "&#xf187;");
            dic.Add("fa-area-chart", "&#xf1fe;");
            dic.Add("fa-arrow-circle-down", "&#xf0ab;");
            dic.Add("fa-arrow-circle-left", "&#xf0a8;");
            dic.Add("fa-arrow-circle-o-down", "&#xf01a;");
            dic.Add("fa-arrow-circle-o-left", "&#xf190;");
            dic.Add("fa-arrow-circle-o-right", "&#xf18e;");
            dic.Add("fa-arrow-circle-o-up", "&#xf01b;");
            dic.Add("fa-arrow-circle-right", "&#xf0a9;");
            dic.Add("fa-arrow-circle-up", "&#xf0aa;");
            dic.Add("fa-arrow-down", "&#xf063;");
            dic.Add("fa-arrow-left", "&#xf060;");
            dic.Add("fa-arrow-right", "&#xf061;");
            dic.Add("fa-arrow-up", "&#xf062;");
            dic.Add("fa-arrows", "&#xf047;");
            dic.Add("fa-arrows-alt", "&#xf0b2;");
            dic.Add("fa-arrows-h", "&#xf07e;");
            dic.Add("fa-arrows-v", "&#xf07d;");
            dic.Add("fa-asterisk", "&#xf069;");
            dic.Add("fa-at", "&#xf1di;");
            dic.Add("fa-automobile (alias)", "&#xf1b9;");
            dic.Add("fa-backward", "&#xf04a;");
            dic.Add("fa-balance-scale", "&#xf24e;");
            dic.Add("fa-ban", "&#xf05e;");
            dic.Add("fa-bank (alias)", "&#xf19c;");
            dic.Add("fa-bar-chart", "&#xf080;");
            dic.Add("fa-bar-chart-o (alias)", "&#xf080;");
            dic.Add("fa-barcode", "&#xf02a;");
            dic.Add("fa-bars", "&#xf0c9;");
            dic.Add("fa-battery-0 (alias)", "&#xf244;");
            dic.Add("fa-battery-1 (alias)", "&#xf243;");
            dic.Add("fa-battery-2 (alias)", "&#xf242;");
            dic.Add("fa-battery-3 (alias)", "&#xf241;");
            dic.Add("fa-battery-4 (alias)", "&#xf240;");
            dic.Add("fa-battery-empty", "&#xf244;");
            dic.Add("fa-battery-full", "&#xf240;");
            dic.Add("fa-battery-half", "&#xf242;");
            dic.Add("fa-battery-quarter", "&#xf243;");
            dic.Add("fa-battery-three-quarters", "&#xf241;");
            dic.Add("fa-bed", "&#xf236;");
            dic.Add("fa-beer", "&#xf0fc;");
            dic.Add("fa-behance", "&#xf1b4;");
            dic.Add("fa-behance-square", "&#xf1b5;");
            dic.Add("fa-bell", "&#xf0f3;");
            dic.Add("fa-bell-o", "&#xf0a2;");
            dic.Add("fa-bell-slash", "&#xf1f6;");
            dic.Add("fa-bell-slash-o", "&#xf1f7;");
            dic.Add("fa-bicycle", "&#xf206;");
            dic.Add("fa-binoculars", "&#xf1e5;");
            dic.Add("fa-birthday-cake", "&#xf1fd;");
            dic.Add("fa-bitbucket", "&#xf171;");
            dic.Add("fa-bitbucket-square", "&#xf172;");
            dic.Add("fa-bitcoin (alias)", "&#xf15a;");
            dic.Add("fa-black-tie", "&#xf27e;");
            dic.Add("fa-bold", "&#xf032;");
            dic.Add("fa-bolt", "&#xf0e7;");
            dic.Add("fa-bomb", "&#xf1e2;");
            dic.Add("fa-book", "&#xf02d;");
            dic.Add("fa-bookmark", "&#xf02e;");
            dic.Add("fa-bookmark-o", "&#xf097;");
            dic.Add("fa-briefcase", "&#xf0b1;");
            dic.Add("fa-btc", "&#xf15a;");
            dic.Add("fa-bug", "&#xf188;");
            dic.Add("fa-building", "&#xf1ad;");
            dic.Add("fa-building-o", "&#xf0f7;");
            dic.Add("fa-bullhorn", "&#xf0a1;");
            dic.Add("fa-bullseye", "&#xf140;");
            dic.Add("fa-bus", "&#xf207;");
            dic.Add("fa-buysellads", "&#xf20d;");
            dic.Add("fa-cab (alias)", "&#xf1ba;");
            dic.Add("fa-calculator", "&#xf1ec;");
            dic.Add("fa-calendar", "&#xf073;");
            dic.Add("fa-calendar-check-o", "&#xf274;");
            dic.Add("fa-calendar-minus-o", "&#xf272;");
            dic.Add("fa-calendar-o", "&#xf133;");
            dic.Add("fa-calendar-plus-o", "&#xf271;");
            dic.Add("fa-calendar-times-o", "&#xf273;");
            dic.Add("fa-camera", "&#xf030;");
            dic.Add("fa-camera-retro", "&#xf083;");
            dic.Add("fa-car", "&#xf1b9;");
            dic.Add("fa-caret-down", "&#xf0d7;");
            dic.Add("fa-caret-left", "&#xf0d9;");
            dic.Add("fa-caret-right", "&#xf0da;");
            dic.Add("fa-caret-square-o-down", "&#xf150;");
            dic.Add("fa-caret-square-o-left", "&#xf191;");
            dic.Add("fa-caret-square-o-right", "&#xf152;");
            dic.Add("fa-caret-square-o-up", "&#xf151;");
            dic.Add("fa-caret-up", "&#xf0d8;");
            dic.Add("fa-cart-arrow-down", "&#xf218;");
            dic.Add("fa-cart-plus", "&#xf217;");
            dic.Add("fa-cc", "&#xf20a;");
            dic.Add("fa-cc-amex", "&#xf1f3;");
            dic.Add("fa-cc-diners-club", "&#xf24c;");
            dic.Add("fa-cc-discover", "&#xf1f2;");
            dic.Add("fa-cc-jcb", "&#xf24b;");
            dic.Add("fa-cc-mastercard", "&#xf1f1;");
            dic.Add("fa-cc-paypal", "&#xf1f4;");
            dic.Add("fa-cc-stripe", "&#xf1f5;");
            dic.Add("fa-cc-visa", "&#xf1f0;");
            dic.Add("fa-certificate", "&#xf0a3;");
            dic.Add("fa-chain (alias)", "&#xf0c1;");
            dic.Add("fa-chain-broken", "&#xf127;");
            dic.Add("fa-check", "&#xf00c;");
            dic.Add("fa-check-circle", "&#xf058;");
            dic.Add("fa-check-circle-o", "&#xf05d;");
            dic.Add("fa-check-square", "&#xf14a;");
            dic.Add("fa-check-square-o", "&#xf046;");
            dic.Add("fa-chevron-circle-down", "&#xf13a;");
            dic.Add("fa-chevron-circle-left", "&#xf137;");
            dic.Add("fa-chevron-circle-right", "&#xf138;");
            dic.Add("fa-chevron-circle-up", "&#xf139;");
            dic.Add("fa-chevron-down", "&#xf078;");
            dic.Add("fa-chevron-left", "&#xf053;");
            dic.Add("fa-chevron-right", "&#xf054;");
            dic.Add("fa-chevron-up", "&#xf077;");
            dic.Add("fa-child", "&#xf1ae;");
            dic.Add("fa-chrome", "&#xf268;");
            dic.Add("fa-circle", "&#xf111;");
            dic.Add("fa-circle-o", "&#xf10c;");
            dic.Add("fa-circle-o-notch", "&#xf1ce;");
            dic.Add("fa-circle-thin", "&#xf1db;");
            dic.Add("fa-clipboard", "&#xf0ea;");
            dic.Add("fa-clock-o", "&#xf017;");
            dic.Add("fa-clone", "&#xf24d;");
            dic.Add("fa-close (alias)", "&#xf00d;");
            dic.Add("fa-cloud", "&#xf0c2;");
            dic.Add("fa-cloud-download", "&#xf0ed;");
            dic.Add("fa-cloud-upload", "&#xf0ee;");
            dic.Add("fa-cny (alias)", "&#xf157;");
            dic.Add("fa-code", "&#xf121;");
            dic.Add("fa-code-fork", "&#xf126;");
            dic.Add("fa-codepen", "&#xf1cb;");
            dic.Add("fa-coffee", "&#xf0f4;");
            dic.Add("fa-cog", "&#xf013;");
            dic.Add("fa-cogs", "&#xf085;");
            dic.Add("fa-columns", "&#xf0db;");
            dic.Add("fa-comment", "&#xf075;");
            dic.Add("fa-comment-o", "&#xf0e5;");
            dic.Add("fa-commenting", "&#xf27a;");
            dic.Add("fa-commenting-o", "&#xf27b;");
            dic.Add("fa-comments", "&#xf086;");
            dic.Add("fa-comments-o", "&#xf0e6;");
            dic.Add("fa-compass", "&#xf14e;");
            dic.Add("fa-compress", "&#xf066;");
            dic.Add("fa-connectdevelop", "&#xf20e;");
            dic.Add("fa-contao", "&#xf26d;");
            dic.Add("fa-copy (alias)", "&#xf0c5;");
            dic.Add("fa-copyright", "&#xf1f9;");
            dic.Add("fa-creative-commons", "&#xf25e;");
            dic.Add("fa-credit-card", "&#xf09d;");
            dic.Add("fa-crop", "&#xf125;");
            dic.Add("fa-crosshairs", "&#xf05b;");
            dic.Add("fa-css3", "&#xf13c;");
            dic.Add("fa-cube", "&#xf1b2;");
            dic.Add("fa-cubes", "&#xf1b3;");
            dic.Add("fa-cut (alias)", "&#xf0c4;");
            dic.Add("fa-cutlery", "&#xf0f5;");
            dic.Add("fa-dashboard (alias)", "&#xf0e4;");
            dic.Add("fa-dashcube", "&#xf210;");
            dic.Add("fa-database", "&#xf1c0;");
            dic.Add("fa-dedent (alias)", "&#xf03b;");
            dic.Add("fa-delicious", "&#xf1a5;");
            dic.Add("fa-desktop", "&#xf108;");
            dic.Add("fa-deviantart", "&#xf1bd;");
            dic.Add("fa-diamond", "&#xf219;");
            dic.Add("fa-digg", "&#xf1a6;");
            dic.Add("fa-dollar (alias)", "&#xf155;");
            dic.Add("fa-dot-circle-o", "&#xf192;");
            dic.Add("fa-download", "&#xf019;");
            dic.Add("fa-dribbble", "&#xf17d;");
            dic.Add("fa-dropbox", "&#xf16b;");
            dic.Add("fa-drupal", "&#xf1a9;");
            dic.Add("fa-edit (alias)", "&#xf044;");
            dic.Add("fa-eject", "&#xf052;");
            dic.Add("fa-ellipsis-h", "&#xf141;");
            dic.Add("fa-ellipsis-v", "&#xf142;");
            dic.Add("fa-empire", "&#xf1d1;");
            dic.Add("fa-envelope", "&#xf0e0;");
            dic.Add("fa-envelope-o", "&#xf003;");
            dic.Add("fa-envelope-square", "&#xf199;");
            dic.Add("fa-eraser", "&#xf12d;");
            dic.Add("fa-eur", "&#xf153;");
            dic.Add("fa-euro (alias)", "&#xf153;");
            dic.Add("fa-exchange", "&#xf0ec;");
            dic.Add("fa-exclamation", "&#xf12a;");
            dic.Add("fa-exclamation-circle", "&#xf06a;");
            dic.Add("fa-exclamation-triangle", "&#xf071;");
            dic.Add("fa-expand", "&#xf065;");
            dic.Add("fa-expeditedssl", "&#xf23e;");
            dic.Add("fa-external-link", "&#xf08e;");
            dic.Add("fa-external-link-square", "&#xf14c;");
            dic.Add("fa-eye", "&#xf06e;");
            dic.Add("fa-eye-slash", "&#xf070;");
            dic.Add("fa-eyedropper", "&#xf1fb;");
            dic.Add("facebook", "&#xf09a;");
            dic.Add("facebook - f(alias)", "&#xf09a;");
            dic.Add("facebook - official", "&#xf230;");
            dic.Add("facebook - square", "&#xf082;");
            dic.Add("fast - backward", "&#xf049;");
            dic.Add("fast - forward", "&#xf050;");
            dic.Add("fax", " &#xf1ac;");
            dic.Add("fa-feed (alias)", "&#xf09e;");
            dic.Add("fa-female", "&#xf182;");
            dic.Add("fa-fighter-jet", "&#xf0fb;");
            dic.Add("fa-file", "&#xf15b;");
            dic.Add("fa-file-archive-o", "&#xf1c6;");
            dic.Add("fa-file-audio-o", "&#xf1c7;");
            dic.Add("fa-file-code-o", "&#xf1c9;");
            dic.Add("fa-file-excel-o", "&#xf1c3;");
            dic.Add("fa-file-image-o", "&#xf1c5;");
            dic.Add("fa-file-movie-o (alias)", "&#xf1c8;");
            dic.Add("fa-file-o", "&#xf016;");
            dic.Add("fa-file-pdf-o", "&#xf1c1;");
            dic.Add("fa-file-photo-o (alias)", "&#xf1c5;");
            dic.Add("fa-file-picture-o (alias)", "&#xf1c5;");
            dic.Add("fa-file-powerpoint-o", "&#xf1c4;");
            dic.Add("fa-file-sound-o (alias)", "&#xf1c7;");
            dic.Add("fa-file-text", "&#xf15c;");
            dic.Add("fa-file-text-o", "&#xf0f6;");
            dic.Add("fa-file-video-o", "&#xf1c8;");
            dic.Add("fa-file-word-o", "&#xf1c2;");
            dic.Add("fa-file-zip-o (alias)", "&#xf1c6;");
            dic.Add("fa-files-o", "&#xf0c5;");
            dic.Add("fa-film", "&#xf008;");
            dic.Add("fa-filter", "&#xf0b0;");
            dic.Add("fa-fire", "&#xf06d;");
            dic.Add("fa-fire-extinguisher", "&#xf134;");
            dic.Add("fa-firefox", "&#xf269;");
            dic.Add("fa-flag", "&#xf024;");
            dic.Add("fa-flag-checkered", "&#xf11e;");
            dic.Add("fa-flag-o", "&#xf11d;");
            dic.Add("fa-flash (alias)", "&#xf0e7;");
            dic.Add("fa-flask", "&#xf0c3;");
            dic.Add("fa-flickr", "&#xf16e;");
            dic.Add("fa-floppy-o", "&#xf0c7;");
            dic.Add("fa-folder", "&#xf07b;");
            dic.Add("fa-folder-o", "&#xf114;");
            dic.Add("fa-folder-open", "&#xf07c;");
            dic.Add("fa-folder-open-o", "&#xf115;");
            dic.Add("fa-font", "&#xf031;");
            dic.Add("fa-fonticons", "&#xf280;");
            dic.Add("fa-forumbee", "&#xf211;");
            dic.Add("fa-forward", "&#xf04e;");
            dic.Add("fa-foursquare", "&#xf180;");
            dic.Add("fa-frown-o", "&#xf119;");
            dic.Add("fa-futbol-o", "&#xf1e3;");
            dic.Add("fa-gamepad", "&#xf11b;");
            dic.Add("fa-gavel", "&#xf0e3;");
            dic.Add("fa-gbp", "&#xf154;");
            dic.Add("fa-ge (alias)", "&#xf1d1;");
            dic.Add("fa-gear (alias)", "&#xf013;");
            dic.Add("fa-gears (alias)", "&#xf085;");
            dic.Add("fa-genderless", "&#xf22d;");
            dic.Add("fa-get-pocket", "&#xf265;");
            dic.Add("fa-gg", "&#xf260;");
            dic.Add("fa-gg-circle", "&#xf261;");
            dic.Add("fa-gift", "&#xf06b;");
            dic.Add("fa-git", "&#xf1d3;");
            dic.Add("fa-git-square", "&#xf1d2;");
            dic.Add("fa-github", "&#xf09b;");
            dic.Add("fa-github-alt", "&#xf113;");
            dic.Add("fa-github-square", "&#xf092;");
            dic.Add("fa-gittip (alias)", "&#xf184;");
            dic.Add("fa-glass", "&#xf000;");
            dic.Add("fa-globe", "&#xf0ac;");
            dic.Add("fa-google", "&#xf1a0;");
            dic.Add("fa-google-plus", "&#xf0d5;");
            dic.Add("fa-google-plus-square", "&#xf0d4;");
            dic.Add("fa-google-wallet", "&#xf1ee;");
            dic.Add("fa-graduation-cap", "&#xf19d;");
            dic.Add("fa-gratipay", "&#xf184;");
            dic.Add("fa-group (alias)", "&#xf0c0;");
            dic.Add("fa-h-square", "&#xf0fd;");
            dic.Add("fa-hacker-news", "&#xf1d4;");
            dic.Add("fa-hand-grab-o (alias)", "&#xf255;");
            dic.Add("fa-hand-lizard-o", "&#xf258;");
            dic.Add("fa-hand-o-down", "&#xf0a7;");
            dic.Add("fa-hand-o-left", "&#xf0a5;");
            dic.Add("fa-hand-o-right", "&#xf0a4;");
            dic.Add("fa-hand-o-up", "&#xf0a6;");
            dic.Add("fa-hand-paper-o", "&#xf256;");
            dic.Add("fa-hand-peace-o", "&#xf25b;");
            dic.Add("fa-hand-pointer-o", "&#xf25a;");
            dic.Add("fa-hand-rock-o", "&#xf255;");
            dic.Add("fa-hand-scissors-o", "&#xf257;");
            dic.Add("fa-hand-spock-o", "&#xf259;");
            dic.Add("fa-hand-stop-o (alias)", "&#xf256;");
            dic.Add("fa-hdd-o", "&#xf0a0;");
            dic.Add("fa-header", "&#xf1dc;");
            dic.Add("fa-headphones", "&#xf025;");
            dic.Add("fa-heart", "&#xf004;");
            dic.Add("fa-heart-o", "&#xf08a;");
            dic.Add("fa-heartbeat", "&#xf21e;");
            dic.Add("fa-history", "&#xf1da;");
            dic.Add("fa-home", "&#xf015;");
            dic.Add("fa-hospital-o", "&#xf0f8;");
            dic.Add("fa-hotel (alias)", "&#xf236;");
            dic.Add("fa-hourglass", "&#xf254;");
            dic.Add("fa-hourglass-1 (alias)", "&#xf251;");
            dic.Add("fa-hourglass-2 (alias)", "&#xf252;");
            dic.Add("fa-hourglass-3 (alias)", "&#xf253;");
            dic.Add("fa-hourglass-end", "&#xf253;");
            dic.Add("fa-hourglass-half", "&#xf252;");
            dic.Add("fa-hourglass-o", "&#xf250;");
            dic.Add("fa-hourglass-start", "&#xf251;");
            dic.Add("fa-houzz", "&#xf27c;");
            dic.Add("fa-html5", "&#xf13b;");
            dic.Add("fa-i-cursor", "&#xf246;");
            dic.Add("fa-ils", "&#xf20b;");
            dic.Add("fa-image (alias)", "&#xf03e;");
            dic.Add("fa-inbox", "&#xf01c;");
            dic.Add("fa-indent", "&#xf03c;");
            dic.Add("fa-industry", "&#xf275;");
            dic.Add("fa-info", "&#xf129;");
            dic.Add("fa-info-circle", "&#xf05a;");
            dic.Add("fa-inr", "&#xf156;");
            dic.Add("fa-instagram", "&#xf16d;");
            dic.Add("fa-institution (alias)", "&#xf19c;");
            dic.Add("fa-internet-explorer", "&#xf26b;");
            dic.Add("fa-intersex (alias)", "&#xf224;");
            dic.Add("fa-ioxhost", "&#xf208;");
            dic.Add("fa-italic", "&#xf033;");
            dic.Add("fa-joomla", "&#xf1aa;");
            dic.Add("fa-jpy", "&#xf157;");
            dic.Add("fa-jsfiddle", "&#xf1cc;");
            dic.Add("fa-key", "&#xf084;");
            dic.Add("fa-keyboard-o", "&#xf11c;");
            dic.Add("fa-krw", "&#xf159;");
            dic.Add("fa-language", "&#xf1ab;");
            dic.Add("fa-laptop", "&#xf109;");
            dic.Add("fa-lastfm", "&#xf202;");
            dic.Add("fa-lastfm-square", "&#xf203;");
            dic.Add("fa-leaf", "&#xf06c;");
            dic.Add("fa-leanpub", "&#xf212;");
            dic.Add("fa-legal (alias)", "&#xf0e3;");
            dic.Add("fa-lemon-o", "&#xf094;");
            dic.Add("fa-level-down", "&#xf149;");
            dic.Add("fa-level-up", "&#xf148;");
            dic.Add("fa-life-bouy (alias)", "&#xf1cd;");
            dic.Add("fa-life-buoy (alias)", "&#xf1cd;");
            dic.Add("fa-life-ring", "&#xf1cd;");
            dic.Add("fa-life-saver (alias)", "&#xf1cd;");
            dic.Add("fa-lightbulb-o", "&#xf0eb;");
            dic.Add("fa-line-chart", "&#xf201;");
            dic.Add("fa-link", "&#xf0c1;");
            dic.Add("fa-linkedin", "&#xf0e1;");
            dic.Add("fa-linkedin-square", "&#xf08c;");
            dic.Add("fa-linux", "&#xf17c;");
            dic.Add("fa-list", "&#xf03a;");
            dic.Add("fa-list-alt", "&#xf022;");
            dic.Add("fa-list-ol", "&#xf0cb;");
            dic.Add("fa-list-ul", "&#xf0ca;");
            dic.Add("fa-location-arrow", "&#xf124;");
            dic.Add("fa-lock", "&#xf023;");
            dic.Add("fa-long-arrow-down", "&#xf175;");
            dic.Add("fa-long-arrow-left", "&#xf177;");
            dic.Add("fa-long-arrow-right", "&#xf178;");
            dic.Add("fa-long-arrow-up", "&#xf176;");
            dic.Add("fa-magic", "&#xf0d0;");
            dic.Add("fa-magnet", "&#xf076;");
            dic.Add("fa-mail-forward (alias)", "&#xf064;");
            dic.Add("fa-mail-reply (alias)", "&#xf112;");
            dic.Add("fa-mail-reply-all (alias)", "&#xf122;");
            dic.Add("fa-male", "&#xf183;");
            dic.Add("fa-map", "&#xf279;");
            dic.Add("fa-map-marker", "&#xf041;");
            dic.Add("fa-map-o", "&#xf278;");
            dic.Add("fa-map-pin", "&#xf276;");
            dic.Add("fa-map-signs", "&#xf277;");
            dic.Add("fa-mars", "&#xf222;");
            dic.Add("fa-mars-double", "&#xf227;");
            dic.Add("fa-mars-stroke", "&#xf229;");
            dic.Add("fa-mars-stroke-h", "&#xf22b;");
            dic.Add("fa-mars-stroke-v", "&#xf22a;");
            dic.Add("fa-maxcdn", "&#xf136;");
            dic.Add("fa-meanpath", "&#xf20c;");
            dic.Add("fa-medium", "&#xf23a;");
            dic.Add("fa-medkit", "&#xf0di;");
            dic.Add("fa-meh-o", "&#xf11a;");
            dic.Add("fa-mercury", "&#xf223;");
            dic.Add("fa-microphone", "&#xf130;");
            dic.Add("fa-microphone-slash", "&#xf131;");
            dic.Add("fa-minus", "&#xf068;");
            dic.Add("fa-minus-circle", "&#xf056;");
            dic.Add("fa-minus-square", "&#xf146;");
            dic.Add("fa-minus-square-o", "&#xf147;");
            dic.Add("fa-mobile", "&#xf10b;");
            dic.Add("fa-mobile-phone (alias)", "&#xf10b;");
            dic.Add("fa-money", "&#xf0d6;");
            dic.Add("fa-moon-o", "&#xf186;");
            dic.Add("fa-mortar-board (alias)", "&#xf19d;");
            dic.Add("fa-motorcycle", "&#xf21c;");
            dic.Add("fa-mouse-pointer", "&#xf245;");
            dic.Add("fa-music", "&#xf001;");
            dic.Add("fa-navicon (alias)", "&#xf0c9;");
            dic.Add("fa-neuter", "&#xf22c;");
            dic.Add("fa-newspaper-o", "&#xf1ea;");
            dic.Add("fa-object-group", "&#xf247;");
            dic.Add("fa-object-ungroup", "&#xf248;");
            dic.Add("fa-odnoklassniki", "&#xf263;");
            dic.Add("fa-odnoklassniki-square", "&#xf264;");
            dic.Add("fa-opencart", "&#xf23d;");
            dic.Add("fa-openid", "&#xf19b;");
            dic.Add("fa-opera", "&#xf26a;");
            dic.Add("fa-optin-monster", "&#xf23c;");
            dic.Add("fa-outdent", "&#xf03b;");
            dic.Add("fa-pagelines", "&#xf18c;");
            dic.Add("fa-paint-brush", "&#xf1fc;");
            dic.Add("fa-paper-plane", "&#xf1d8;");
            dic.Add("fa-paper-plane-o", "&#xf1d9;");
            dic.Add("fa-paperclip", "&#xf0c6;");
            dic.Add("fa-paragraph", "&#xf1dd;");
            dic.Add("fa-paste (alias)", "&#xf0ea;");
            dic.Add("fa-pause", "&#xf04c;");
            dic.Add("fa-paw", "&#xf1b0;");
            dic.Add("fa-paypal", "&#xf1ed;");
            dic.Add("fa-pencil", "&#xf040;");
            dic.Add("fa-pencil-square", "&#xf14b;");
            dic.Add("fa-pencil-square-o", "&#xf044;");
            dic.Add("fa-phone", "&#xf095;");
            dic.Add("fa-phone-square", "&#xf098;");
            dic.Add("fa-photo (alias)", "&#xf03e;");
            dic.Add("fa-picture-o", "&#xf03e;");
            dic.Add("fa-pie-chart", "&#xf200;");
            dic.Add("fa-pied-piper", "&#xf1a7;");
            dic.Add("fa-pied-piper-alt", "&#xf1a8;");
            dic.Add("fa-pinterest", "&#xf0d2;");
            dic.Add("fa-pinterest-p", "&#xf231;");
            dic.Add("fa-pinterest-square", "&#xf0d3;");
            dic.Add("fa-plane", "&#xf072;");
            dic.Add("fa-play", "&#xf04b;");
            dic.Add("fa-play-circle", "&#xf144;");
            dic.Add("fa-play-circle-o", "&#xf01d;");
            dic.Add("fa-plug", "&#xf1e6;");
            dic.Add("fa-plus", "&#xf067;");
            dic.Add("fa-plus-circle", "&#xf055;");
            dic.Add("fa-plus-square", "&#xf0fe;");
            dic.Add("fa-plus-square-o", "&#xf196;");
            dic.Add("fa-power-off", "&#xf011;");
            dic.Add("fa-print", "&#xf02f;");
            dic.Add("fa-puzzle-piece", "&#xf12e;");
            dic.Add("fa-qq", "&#xf1d6;");
            dic.Add("fa-qrcode", "&#xf029;");
            dic.Add("fa-question", "&#xf128;");
            dic.Add("fa-question-circle", "&#xf059;");
            dic.Add("fa-quote-left", "&#xf10d;");
            dic.Add("fa-quote-right", "&#xf10e;");
            dic.Add("fa-ra (alias)", "&#xf1d0;");
            dic.Add("fa-random", "&#xf074;");
            dic.Add("fa-rebel", "&#xf1d0;");
            dic.Add("fa-recycle", "&#xf1b8;");
            dic.Add("fa-reddit", "&#xf1a1;");
            dic.Add("fa-reddit-square", "&#xf1a2;");
            dic.Add("fa-refresh", "&#xf021;");
            dic.Add("fa-registered", "&#xf25d;");
            dic.Add("fa-remove (alias)", "&#xf00d;");
            dic.Add("fa-renren", "&#xf18b;");
            dic.Add("fa-reorder (alias)", "&#xf0c9;");
            dic.Add("fa-repeat", "&#xf01e;");
            dic.Add("fa-reply", "&#xf112;");
            dic.Add("fa-reply-all", "&#xf122;");
            dic.Add("fa-retweet", "&#xf079;");
            dic.Add("fa-rmb (alias)", "&#xf157;");
            dic.Add("fa-road", "&#xf018;");
            dic.Add("fa-rocket", "&#xf135;");
            dic.Add("fa-rotate-left (alias)", "&#xf0e2;");
            dic.Add("fa-rotate-right (alias)", "&#xf01e;");
            dic.Add("fa-rouble (alias)", "&#xf158;");
            dic.Add("fa-rss", "&#xf09e;");
            dic.Add("fa-rss-square", "&#xf143;");
            dic.Add("fa-rub", "&#xf158;");
            dic.Add("fa-ruble (alias)", "&#xf158;");
            dic.Add("fa-rupee (alias)", "&#xf156;");
            dic.Add("fari", " &#xf267;");
            dic.Add("fa-save (alias)", "&#xf0c7;");
            dic.Add("fa-scissors", "&#xf0c4;");
            dic.Add("fa-search", "&#xf002;");
            dic.Add("fa-search-minus", "&#xf010;");
            dic.Add("fa-search-plus", "&#xf00e;");
            dic.Add("fa-sellsy", "&#xf213;");
            dic.Add("fa-send (alias)", "&#xf1d8;");
            dic.Add("fa-send-o (alias)", "&#xf1d9;");
            dic.Add("fa-server", "&#xf233;");
            dic.Add("fa-share", "&#xf064;");
            dic.Add("fa-share-alt", "&#xf1e0;");
            dic.Add("fa-share-alt-square", "&#xf1e1;");
            dic.Add("fa-share-square", "&#xf14d;");
            dic.Add("fa-share-square-o", "&#xf045;");
            dic.Add("fa-shekel (alias)", "&#xf20b;");
            dic.Add("fa-sheqel (alias)", "&#xf20b;");
            dic.Add("fa-shield", "&#xf132;");
            dic.Add("fa-ship", "&#xf21a;");
            dic.Add("fa-shirtsinbulk", "&#xf214;");
            dic.Add("fa-shopping-cart", "&#xf07a;");
            dic.Add("fa-sign-in", "&#xf090;");
            dic.Add("fa-sign-out", "&#xf08b;");
            dic.Add("fa-signal", "&#xf012;");
            dic.Add("fa-simplybuilt", "&#xf215;");
            dic.Add("fa-sitemap", "&#xf0e8;");
            dic.Add("fa-skyatlas", "&#xf216;");
            dic.Add("fa-skype", "&#xf17e;");
            dic.Add("fa-slack", "&#xf198;");
            dic.Add("fa-sliders", "&#xf1de;");
            dic.Add("fa-slideshare", "&#xf1e7;");
            dic.Add("fa-smile-o", "&#xf118;");
            dic.Add("fa-soccer-ball-o (alias)", "&#xf1e3;");
            dic.Add("fa-sort", "&#xf0dc;");
            dic.Add("fa-sort-alpha-asc", "&#xf15d;");
            dic.Add("fa-sort-alpha-desc", "&#xf15e;");
            dic.Add("fa-sort-amount-asc", "&#xf160;");
            dic.Add("fa-sort-amount-desc", "&#xf161;");
            dic.Add("fa-sort-asc", "&#xf0de;");
            dic.Add("fa-sort-desc", "&#xf0dd;");
            dic.Add("fa-sort-down (alias)", "&#xf0dd;");
            dic.Add("fa-sort-numeric-asc", "&#xf162;");
            dic.Add("fa-sort-numeric-desc", "&#xf163;");
            dic.Add("fa-sort-up (alias)", "&#xf0de;");
            dic.Add("fa-soundcloud", "&#xf1be;");
            dic.Add("fa-space-shuttle", "&#xf197;");
            dic.Add("fa-spinner", "&#xf110;");
            dic.Add("fa-spoon", "&#xf1b1;");
            dic.Add("fa-spotify", "&#xf1bc;");
            dic.Add("fa-square", "&#xf0c8;");
            dic.Add("fa-square-o", "&#xf096;");
            dic.Add("fa-stack-exchange", "&#xf18d;");
            dic.Add("fa-stack-overflow", "&#xf16c;");
            dic.Add("fa-star", "&#xf005;");
            dic.Add("fa-star-half", "&#xf089;");
            dic.Add("fa-star-half-empty (alias)", "&#xf123;");
            dic.Add("fa-star-half-full (alias)", "&#xf123;");
            dic.Add("fa-star-half-o", "&#xf123;");
            dic.Add("fa-star-o", "&#xf006;");
            dic.Add("fa-steam", "&#xf1b6;");
            dic.Add("fa-steam-square", "&#xf1b7;");
            dic.Add("fa-step-backward", "&#xf048;");
            dic.Add("fa-step-forward", "&#xf051;");
            dic.Add("fa-stethoscope", "&#xf0f1;");
            dic.Add("fa-sticky-note", "&#xf249;");
            dic.Add("fa-sticky-note-o", "&#xf24a;");
            dic.Add("fa-stop", "&#xf04d;");
            dic.Add("fa-street-view", "&#xf21d;");
            dic.Add("fa-strikethrough", "&#xf0cc;");
            dic.Add("fa-stumbleupon", "&#xf1a4;");
            dic.Add("fa-stumbleupon-circle", "&#xf1a3;");
            dic.Add("fa-subscript", "&#xf12c;");
            dic.Add("fa-subway", "&#xf239;");
            dic.Add("fa-suitcase", "&#xf0f2;");
            dic.Add("fa-sun-o", "&#xf185;");
            dic.Add("fa-superscript", "&#xf12b;");
            dic.Add("fa-support (alias)", "&#xf1cd;");
            dic.Add("fa-table", "&#xf0ce;");
            dic.Add("fa-tablet", "&#xf10a;");
            dic.Add("fa-tachometer", "&#xf0e4;");
            dic.Add("fa-tag", "&#xf02b;");
            dic.Add("fa-tags", "&#xf02c;");
            dic.Add("fa-tasks", "&#xf0ae;");
            dic.Add("fa-taxi", "&#xf1ba;");
            dic.Add("fa-television", "&#xf26c;");
            dic.Add("fa-tencent-weibo", "&#xf1d5;");
            dic.Add("fa-terminal", "&#xf120;");
            dic.Add("fa-text-height", "&#xf034;");
            dic.Add("fa-text-width", "&#xf035;");
            dic.Add("fa-th", "&#xf00a;");
            dic.Add("fa-th-large", "&#xf009;");
            dic.Add("fa-th-list", "&#xf00b;");
            dic.Add("fa-thumb-tack", "&#xf08d;");
            dic.Add("fa-thumbs-down", "&#xf165;");
            dic.Add("fa-thumbs-o-down", "&#xf088;");
            dic.Add("fa-thumbs-o-up", "&#xf087;");
            dic.Add("fa-thumbs-up", "&#xf164;");
            dic.Add("fa-ticket", "&#xf145;");
            dic.Add("fa-times", "&#xf00d;");
            dic.Add("fa-times-circle", "&#xf057;");
            dic.Add("fa-times-circle-o", "&#xf05c;");
            dic.Add("fa-tint", "&#xf043;");
            dic.Add("fa-toggle-down (alias)", "&#xf150;");
            dic.Add("fa-toggle-left (alias)", "&#xf191;");
            dic.Add("fa-toggle-off", "&#xf204;");
            dic.Add("fa-toggle-on", "&#xf205;");
            dic.Add("fa-toggle-right (alias)", "&#xf152;");
            dic.Add("fa-toggle-up (alias)", "&#xf151;");
            dic.Add("fa-trademark", "&#xf25c;");
            dic.Add("fa-train", "&#xf238;");
            dic.Add("fa-transgender", "&#xf224;");
            dic.Add("fa-transgender-alt", "&#xf225;");
            dic.Add("fa-trash", "&#xf1f8;");
            dic.Add("fa-trash-o", "&#xf014;");
            dic.Add("fa-tree", "&#xf1bb;");
            dic.Add("fa-trello", "&#xf181;");
            dic.Add("fa-tripadvisor", "&#xf262;");
            dic.Add("fa-trophy", "&#xf091;");
            dic.Add("fa-truck", "&#xf0d1;");
            dic.Add("fa-try", "&#xf195;");
            dic.Add("fa-tty", "&#xf1e4;");
            dic.Add("fa-tumblr", "&#xf173;");
            dic.Add("fa-tumblr-square", "&#xf174;");
            dic.Add("fa-turkish-lira (alias)", "&#xf195;");
            dic.Add("fa-tv (alias)", "&#xf26c;");
            dic.Add("fa-twitch", "&#xf1e8;");
            dic.Add("fa-twitter", "&#xf099;");
            dic.Add("fa-twitter-square", "&#xf081;");
            dic.Add("fa-umbrella", "&#xf0e9;");
            dic.Add("fa-underline", "&#xf0cd;");
            dic.Add("fa-undo", "&#xf0e2;");
            dic.Add("fa-university", "&#xf19c;");
            dic.Add("fa-unlink (alias)", "&#xf127;");
            dic.Add("fa-unlock", "&#xf09c;");
            dic.Add("fa-unlock-alt", "&#xf13e;");
            dic.Add("fa-unsorted (alias)", "&#xf0dc;");
            dic.Add("fa-upload", "&#xf093;");
            dic.Add("fa-usd", "&#xf155;");
            dic.Add("fa-user", "&#xf007;");
            dic.Add("fa-user-md", "&#xf0f0;");
            dic.Add("fa-user-plus", "&#xf234;");
            dic.Add("fa-user-secret", "&#xf21b;");
            dic.Add("fa-user-times", "&#xf235;");
            dic.Add("fa-users", "&#xf0c0;");
            dic.Add("fa-venus", "&#xf221;");
            dic.Add("fa-venus-double", "&#xf226;");
            dic.Add("fa-venus-mars", "&#xf228;");
            dic.Add("fa-viacoin", "&#xf237;");
            dic.Add("fa-video-camera", "&#xf03d;");
            dic.Add("fa-vimeo", "&#xf27d;");
            dic.Add("fa-vimeo-square", "&#xf194;");
            dic.Add("fa-vine", "&#xf1ca;");
            dic.Add("fa-vk", "&#xf189;");
            dic.Add("fa-volume-down", "&#xf027;");
            dic.Add("fa-volume-off", "&#xf026;");
            dic.Add("fa-volume-up", "&#xf028;");
            dic.Add("fa-warning (alias)", "&#xf071;");
            dic.Add("fa-wechat (alias)", "&#xf1d7;");
            dic.Add("fa-weibo", "&#xf18a;");
            dic.Add("fa-weixin", "&#xf1d7;");
            dic.Add("fa-whatsapp", "&#xf232;");
            dic.Add("fa-wheelchair", "&#xf193;");
            dic.Add("fa-wifi", "&#xf1eb;");
            dic.Add("fa-wikipedia-w", "&#xf266;");
            dic.Add("fa-windows", "&#xf17a;");
            dic.Add("fa-won (alias)", "&#xf159;");
            dic.Add("fa-wordpress", "&#xf19a;");
            dic.Add("fa-wrench", "&#xf0ad;");
            dic.Add("fa-xing", "&#xf168;");
            dic.Add("fa-xing-square", "&#xf169;");
            dic.Add("fa-y-combinator", "&#xf23b;");
            dic.Add("fa-y-combinator-square (alias)", "&#xf1d4;");
            dic.Add("fa-yahoo", "&#xf19e;");
            dic.Add("fa-yc (alias)", "&#xf23b;");
            dic.Add("fa-yc-square (alias)", "&#xf1d4;");
            dic.Add("fa-yelp", "&#xf1e9;");
            dic.Add("fa-yen (alias)", "&#xf157;");
            dic.Add("fa-youtube", "&#xf167;");
            dic.Add("fa-youtube-play", "&#xf16a;");
            dic.Add("fa-youtube-square", "&#xf166;");
            #endregion
        }
        public static string GetUnicode(string name)
        {
            return dic[name];
        }
    }
}
